name: attendo
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_screenutil: ^5.9.0
  google_fonts: ^6.2.1
  go_router: ^13.2.0
  camera: ^0.10.5+9
  image_gallery_saver: ^2.0.3
  permission_handler: ^11.3.1
  google_mlkit_object_detection: ^0.11.0
  flutter_svg: ^2.0.7
  qr_flutter: ^4.1.0
  lottie: ^3.1.0
  flutter_native_splash: ^2.3.13
#  mobile_scanner: ^5.0.0
  image: ^4.1.1
  flutter_localizations:
    sdk: flutter
  intl: any
  shared_preferences: ^2.2.3
  flutter_bloc: ^8.1.5



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/splash/
    - assets/images/
    - assets/lottie/
    - assets/images/svg/
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
