name: "Build & Release"

on:
  pull_request:
    branches:
      - dev
      - test
  push:
    branches:
      - dev
      - test
      
  workflow_dispatch:


jobs:
  build:
    name: Build & Release
    runs-on: macos-latest

    steps:
        #1 Checkout repository
      - name: Checkout Repository
        uses: actions/checkout@v3

        #2 setup java
      - name: Set Up Java
        uses: actions/setup-java@v3.12.0
        with:
          distribution: 'oracle'
          java-version: '17'

        #3 setup Flutter
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64

        #4 install dependencies
      - name: Install Dependencies
        run: flutter pub get

        #6 build apk
      - name: Build APK
        run: flutter build apk --release

        #8 build ipa
      - run: flutter build ios --release --no-codesign

      - run: mkdir Payload
        working-directory: build/ios/iphoneos

      - run: mv Runner.app/ Payload
        working-directory: build/ios/iphoneos

      - name: Zip output
        run: zip -qq -r -9 FlutterIpaExport.ipa Payload
        working-directory: build/ios/iphoneos


        #9 get those build to be available to download
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Releases
          path: |
            build/app/outputs/flutter-apk/app-release.apk
            build/ios/iphoneos/FlutterIpaExport.ipa

        #10 create release with those builds 
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/flutter-apk/app-release.apk,build/ios/iphoneos/FlutterIpaExport.ipa"
          tag: v1.0.${{ github.run_number }}
          token: ${{ secrets.TOKEN }}
